require 'bundler'
Bundler.setup

desc "environment"
task :environment do
  ENV['RACK_ENV'] ||= 'development'
  Mongoid.load!("config/mongoid.yml")
  Moped::logger = Logger.new STDOUT
end

require File.join(File.dirname(__FILE__), '..', 'lib', 'mongoid_migrations')
require File.join(File.dirname(__FILE__), 'models', 'test_model')
